#!/bin/bash
# Usage: Hello World Bash Shell Script Using Variables
# Author: Naveen Kumar M
# -------------------------------------------------
 
# Define bash shell variable called var 
# Avoid spaces around the assignment operator (=)
var="Hello World"
 
# print it 
echo "$var"
 
# Another way of printing it
printf "%s\n" "$var"
